name: Roger Monteiro
description: Blogging about Tec Dev
meta_description: "Roger Monteiro, Blogging about Tec Dev"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /kasper
domain_name: "http://rogermonteiro124.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Your Name"

# Disqus config
disqus-shortname: ""
